### Custom layers

In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [2]:
tf.enable_eager_execution()

In [4]:
# Layers: common sets of useful operations
# In the tf.keras.layers package, layers are objects. to construct a layer,
# simply contruct the object. most layers take as a first argument the number of 
# ouput dimensions / channels.
layer = tf.keras.layers.Dense(100)
# the number of input dimensions is often unnecessary, as it can be inferred
# the first time the layer used, but it can be provided if you want to 
# specify it manually, which is useful in some complex models.
layer = tf.keras.layers.Dense(10, input_shape=(None, 5))

In [5]:
# To use a layer, simply call it
layer(tf.zeros([10, 5]))

<tf.Tensor: id=30, shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [6]:
# layers have many useful methods. for example, you can inspect all variables in
# a layer by calling layer.variables, in this case a fully-connected layer will
# have vatiables for weights and biases.
layer.variables

[<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.06401575,  0.14362425,  0.59677035, -0.11977607,  0.0079816 ,
          0.47780448,  0.23626924,  0.21693671,  0.50511616,  0.01997006],
        [-0.48665026, -0.3286733 , -0.5390564 , -0.10435969,  0.330172  ,
          0.5658696 , -0.5130405 , -0.00140071, -0.4196869 , -0.06027919],
        [ 0.42531365, -0.33070683, -0.4918769 ,  0.47336394,  0.20002103,
         -0.16844052, -0.57393634, -0.12991405,  0.20814979,  0.2425353 ],
        [ 0.16692674,  0.2036804 , -0.21104601, -0.0700773 , -0.06780523,
          0.50103754,  0.38384598,  0.18435329, -0.5712487 ,  0.14806831],
        [ 0.4653178 ,  0.6107562 ,  0.09184206, -0.52241427,  0.38143653,
         -0.48524657, -0.22209537, -0.36559778, -0.33325112, -0.34652388]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>]

In [9]:
# the variables are also accessible through nice accessors
layer.kernel, layer.bias

(<tf.Variable 'dense_3/kernel:0' shape=(5, 10) dtype=float32, numpy=
 array([[ 0.06401575,  0.14362425,  0.59677035, -0.11977607,  0.0079816 ,
          0.47780448,  0.23626924,  0.21693671,  0.50511616,  0.01997006],
        [-0.48665026, -0.3286733 , -0.5390564 , -0.10435969,  0.330172  ,
          0.5658696 , -0.5130405 , -0.00140071, -0.4196869 , -0.06027919],
        [ 0.42531365, -0.33070683, -0.4918769 ,  0.47336394,  0.20002103,
         -0.16844052, -0.57393634, -0.12991405,  0.20814979,  0.2425353 ],
        [ 0.16692674,  0.2036804 , -0.21104601, -0.0700773 , -0.06780523,
          0.50103754,  0.38384598,  0.18435329, -0.5712487 ,  0.14806831],
        [ 0.4653178 ,  0.6107562 ,  0.09184206, -0.52241427,  0.38143653,
         -0.48524657, -0.22209537, -0.36559778, -0.33325112, -0.34652388]],
       dtype=float32)>,
 <tf.Variable 'dense_3/bias:0' shape=(10,) dtype=float32, numpy=array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)>)

In [11]:
# Inplementing custom layers
class MyDenseLayer(tf.keras.layers.Layer):
    def __init__(self, num_outputs):
        super(MyDenseLayer, self).__init__()
        self.num_outputs = num_outputs
    
    def build(self, input_shape):
        self.kernel = self.add_variable('kernel', shape=[input_shape[-1].value, self.num_outputs])
        
    def call(self, input):
        return tf.matmul(input, self.kernel)

layer = MyDenseLayer(10)
print(layer(tf.zeros([10, 5])))
print(layer.variables)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]], shape=(10, 10), dtype=float32)
[<tf.Variable 'my_dense_layer/kernel:0' shape=(5, 10) dtype=float32, numpy=
array([[-0.58138657,  0.24897552, -0.04616696, -0.2143679 , -0.3425806 ,
         0.06120473,  0.3705284 , -0.6223701 ,  0.07423669,  0.41329616],
       [-0.04668128,  0.282467  ,  0.21983474, -0.20020893,  0.35261256,
        -0.5524509 ,  0.04037005,  0.05408776, -0.5731471 , -0.48651877],
       [ 0.39086443, -0.07081753,  0.09407705,  0.3160625 ,  0.56485754,
         0.09129995,  0.54359883, -0.03128153, -0.41091716, -0.51546985],
       [-0.49866408,  0.55272156,  0.4355901 , -0.15723947, -0.5633368 ,
        -0.6024993 , -0.24919716,  0

In [12]:
# Models: composing layers
class ResnetIdentityBlock(tf.keras.Model):
    def __init__(self, kernel_size, filters):
        super(ResnetIdentityBlock, self).__init__()
        filters1, filters2, filters3 = filters
        
        self.conv2a = tf.keras.layers.Conv2D(filters1, (1, 1))
        self.bn2a = tf.keras.layers.BatchNormalization()
        
        self.conv2b = tf.keras.layers.Conv2D(filters2, kernel_size, padding='same')
        self.bn2b = tf.keras.layers.BatchNormalization()
        
        self.conv2c = tf.keras.layers.Conv2D(filters3, (1, 1))
        self.bn2c = tf.keras.layers.BatchNormalization()
        
    def call(self, input_tensor, training=False):
        x = self.conv2a(input_tensor)
        x = self.bn2a(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2b(x)
        x = self.bn2b(x, training=training)
        x = tf.nn.relu(x)
        
        x = self.conv2c(x)
        x = self.bn2c(x, training=training)
        
        x += input_tensor
        return tf.nn.relu(x)
    
block = ResnetIdentityBlock(1, [1, 2, 3])
print(block(tf.zeros([1, 2, 3, 3])))
print([x.name for x in block.variables])

tf.Tensor(
[[[[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]

  [[0. 0. 0.]
   [0. 0. 0.]
   [0. 0. 0.]]]], shape=(1, 2, 3, 3), dtype=float32)
['resnet_identity_block/conv2d/kernel:0', 'resnet_identity_block/conv2d/bias:0', 'resnet_identity_block/batch_normalization/gamma:0', 'resnet_identity_block/batch_normalization/beta:0', 'resnet_identity_block/conv2d_1/kernel:0', 'resnet_identity_block/conv2d_1/bias:0', 'resnet_identity_block/batch_normalization_1/gamma:0', 'resnet_identity_block/batch_normalization_1/beta:0', 'resnet_identity_block/conv2d_2/kernel:0', 'resnet_identity_block/conv2d_2/bias:0', 'resnet_identity_block/batch_normalization_2/gamma:0', 'resnet_identity_block/batch_normalization_2/beta:0', 'resnet_identity_block/batch_normalization/moving_mean:0', 'resnet_identity_block/batch_normalization/moving_variance:0', 'resnet_identity_block/batch_normalization_1/moving_mean:0', 'resnet_identity_block/batch_normalization_1/moving_variance:0', 'resnet_identity_block/batch_normalization_2

In [13]:
my_seq = tf.keras.Sequential([
    tf.keras.layers.Conv2D(1, (1, 1)),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(2, 1, padding='same'),
    tf.keras.layers.BatchNormalization(),
    tf.keras.layers.Conv2D(3, (1, 1)),
    tf.keras.layers.BatchNormalization()
])

my_seq(tf.zeros([1, 2, 3, 3]))

<tf.Tensor: id=514, shape=(1, 2, 3, 3), dtype=float32, numpy=
array([[[[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]]], dtype=float32)>